### ISSUE TITLE
How did you get the GitHub Action to work?

### ISSUE THREAD

**Issue by thejohnfreeman** [jtwebman/coveralls-next#1]
I see you've got [coverage results for this project](https://coveralls.io/github/jtwebman/coveralls-next?branch=master) on coveralls.io. I've tried copying the same [workflow](https://github.com/thejohnfreeman/node-find/blob/master/.github/workflows/test.yml) for my project, and while it successfully uploads to coveralls.io, it seems to always report [0% coverage](https://coveralls.io/github/thejohnfreeman/node-find?branch=master), even though I can see the individual jobs in GitHub actions [calculate](https://github.com/thejohnfreeman/node-find/runs/2098921213?check_suite_focus=true) [non-zero](https://github.com/thejohnfreeman/node-find/runs/2098921231?check_suite_focus=true) [coverage](https://github.com/thejohnfreeman/node-find/runs/2098921252?check_suite_focus=true).

What are you doing different that makes it work? Is it the [`CI = true` environment variable](https://github.com/jtwebman/coveralls-next/blob/master/.github/workflows/test.yml#L3-L4)? Are you setting a secret `COVERALLS_REPO_TOKEN`, even though the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action) never mentions it? Thanks for any help you can offer.

**Comment by jtwebman** [comment]
Sorry for the delay. You used the `parallel: true` so you need to add the finished job at the bottom like is done here: https://github.com/jtwebman/coveralls-next/blob/master/.github/workflows/test.yml#L42 Or you just need to set that false or not set it at all. This doesn't use my next library and doesn't require you have any coveralls installed at all.

**Comment by thejohnfreeman** [comment]
> you need to add the finished job at the bottom like is done here

That's exactly what I had done, [here](https://github.com/thejohnfreeman/node-find/blob/master/.github/workflows/test.yml#L35-L44), on [March 12](https://github.com/thejohnfreeman/node-find/commit/df10b352e939fbd550d6d4737dcc1289cf3368b0). Checking Coveralls now, though, I see it reports non-zero coverage for my tests starting March 30, so I guess there was just some serious latency between submitting reports and seeing them on Coveralls.

**Comment by jtwebman** [comment]
Yes, I have had many issues with them. I wish there was a better option out there but I like the badge.
